import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-emerald-100">
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home my-aircut</div>
      <div>home -aircut</div>
      <div>home my-aircut</div>
    </div>
  )
}
